/*
 * This file is part of nodevmap open source project.
 *
 * For conditions of distribution and use, see copyright notice in LICENSE file.
 *
 * For more detailed information : https://github.com/moveplaten
 */

#pragma once

#include "test_common.h"

static const char* plist_array_03 = INIT_STRING
(

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
    <array>
        <data>
        MzMTQg==
        </data>
        <data>
        MzMjQg==
        </data>
        <data>
        zcw6Qw==
        </data>
        <data>
        zcw+Qw==
        </data>
        <data>
        S8suyA==
        </data>
    </array>
    <array>
        <array>
            <data>
            NDOrQg==
            </data>
            <data>
            AACYQg==
            </data>
            <data>
            mpkgQw==
            </data>
            <data>
            AAAXQw==
            </data>
            <data>
            lkYTyA==
            </data>
        </array>
        <array>
            <array>
                <data>
                mJmZQQ==
                </data>
                <data>
                yMysQQ==
                </data>
                <data>
                zMxiQg==
                </data>
                <data>
                ZGZsQg==
                </data>
                <data>
                bFTPyA==
                </data>
            </array>
            <array>
                <array>
                    <data>
                    yMyMQQ==
                    </data>
                    <data>
                    AACAQQ==
                    </data>
                    <data>
                    ZGYRQg==
                    </data>
                    <data>
                    AAALQg==
                    </data>
                    <data>
                    1YvoyA==
                    </data>
                </array>
            </array>
        </array>
        <array>
            <data>
            mpmZQQ==
            </data>
            <data>
            zMxMQQ==
            </data>
            <data>
            Zma8Qg==
            </data>
            <data>
            mpmvQg==
            </data>
            <data>
            +P7RyA==
            </data>
        </array>
        <array>
            <array>
                <data>
                AABAQQ==
                </data>
                <data>
                ODMzQQ==
                </data>
                <data>
                AABGQg==
                </data>
                <data>
                z8xCQg==
                </data>
                <data>
                Lv30yA==
                </data>
            </array>
            <array>
                <array>
                    <data>
                    aGZmQQ==
                    </data>
                    <data>
                    AABAQQ==
                    </data>
                    <data>
                    mpkEQg==
                    </data>
                    <data>
                    AAD2QQ==
                    </data>
                    <data>
                    ohy2yA==
                    </data>
                </array>
            </array>
        </array>
    </array>
    <array>
        <data>
        mpmJQw==
        </data>
        <data>
        MzOLQg==
        </data>
        <data>
        mpnUQw==
        </data>
        <data>
        mplbQw==
        </data>
        <data>
        /dl8yA==
        </data>
    </array>
    <array>
        <array>
            <data>
            kJm5QQ==
            </data>
            <data>
            aGbGQQ==
            </data>
            <data>
            ZGbEQg==
            </data>
            <data>
            mpnHQg==
            </data>
            <data>
            5lqRyA==
            </data>
        </array>
        <array>
            <array>
                <data>
                wMzMQA==
                </data>
                <data>
                0MzMQA==
                </data>
                <data>
                mJkvQg==
                </data>
                <data>
                mZkvQg==
                </data>
                <data>
                5Pb4yA==
                </data>
            </array>
            <array>
                <array>
                    <data>
                    0MyMQQ==
                    </data>
                    <data>
                    YGZmQQ==
                    </data>
                    <data>
                    aGYRQg==
                    </data>
                    <data>
                    mJkEQg==
                    </data>
                    <data>
                    ltCqyA==
                    </data>
                </array>
            </array>
            <array>
                <data>
                0MxMQg==
                </data>
                <data>
                ZmYWQg==
                </data>
                <data>
                aGaxQg==
                </data>
                <data>
                MjOWQg==
                </data>
                <data>
                lfGFyA==
                </data>
            </array>
            <array>
                <array>
                    <data>
                    wMxMQQ==
                    </data>
                    <data>
                    AACAQQ==
                    </data>
                    <data>
                    YGb8QQ==
                    </data>
                    <data>
                    AAALQg==
                    </data>
                    <data>
                    zgNXyA==
                    </data>
                </array>
            </array>
        </array>
    </array>
    <array>
        <data>
        mpl5Qg==
        </data>
        <data>
        zcx4Qw==
        </data>
        <data>
        ZmZUQw==
        </data>
        <data>
        ZmbHQw==
        </data>
        <data>
        nT3qyA==
        </data>
    </array>
    <array>
        <array>
            <data>
            NDOzQQ==
            </data>
            <data>
            mJmZQQ==
            </data>
            <data>
            zczCQg==
            </data>
            <data>
            ZWa8Qg==
            </data>
            <data>
            lcu7yA==
            </data>
        </array>
        <array>
            <data>
            MzPrQg==
            </data>
            <data>
            ZmaeQg==
            </data>
            <data>
            mplAQw==
            </data>
            <data>
            MjMaQw==
            </data>
            <data>
            /f7+yA==
            </data>
        </array>
    </array>
    <array>
        <data>
        ZmaOQw==
        </data>
        <data>
        AACEQw==
        </data>
        <data>
        ZmbZQw==
        </data>
        <data>
        AADPQw==
        </data>
        <data>
        EeEfyA==
        </data>
    </array>
    <array>
        <array>
            <data>
            QDMzQQ==
            </data>
            <data>
            oJkZQQ==
            </data>
            <data>
            aGasQg==
            </data>
            <data>
            NDOpQg==
            </data>
            <data>
            1ICvyA==
            </data>
        </array>
        <array>
            <array>
                <data>
                AABAQQ==
                </data>
                <data>
                oJkZQQ==
                </data>
                <data>
                AABGQg==
                </data>
                <data>
                aGY8Qg==
                </data>
                <data>
                pennyA==
                </data>
            </array>
            <array>
                <array>
                    <data>
                    MDOTQQ==
                    </data>
                    <data>
                    YGamQQ==
                    </data>
                    <data>
                    mJkUQg==
                    </data>
                    <data>
                    MDMeQg==
                    </data>
                    <data>
                    hZvayA==
                    </data>
                </array>
            </array>
            <array>
                <data>
                MDNjQg==
                </data>
                <data>
                aGZWQg==
                </data>
                <data>
                mJm8Qg==
                </data>
                <data>
                NDO2Qg==
                </data>
                <data>
                9k60yA==
                </data>
            </array>
        </array>
        <array>
            <data>
            0MycQg==
            </data>
            <data>
            NDPDQg==
            </data>
            <data>
            aGYZQw==
            </data>
            <data>
            mpksQw==
            </data>
            <data>
            if10yA==
            </data>
        </array>
        <array>
            <array>
                <data>
                YGaGQQ==
                </data>
                <data>
                YGaGQQ==
                </data>
                <data>
                MDNZQg==
                </data>
                <data>
                MDNZQg==
                </data>
                <data>
                MP6iyA==
                </data>
            </array>
            <array>
                <array>
                    <data>
                    oJm5QQ==
                    </data>
                    <data>
                    AACgQQ==
                    </data>
                    <data>
                    0MwnQg==
                    </data>
                    <data>
                    AAAbQg==
                    </data>
                    <data>
                    y+xDyA==
                    </data>
                </array>
            </array>
        </array>
    </array>
</array>
</plist>

)
