#pragma once

#include "test_common.h"

static const char* plist_array_04 = INIT_STRING
(

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
    <array>
        <data>
        AABAQc3MrEEAACJDmpkrQw==
        </data>
        <data>
        AkvLLsgA
        </data>
        <data>
        A0vLLsgABgAAAGdpdGh1YgAAAAAAAAAAAABwQQ==
        </data>
        <data>
        Adzc3MgAAAAAAAAAAAAAABZDAAAWQw==
        </data>
    </array>
    <array>
        <array>
            <data>
            AADIQmdmhkIAAC9DNDMOQw==
            </data>
            <data>
            AqT+dMgA
            </data>
            <data>
            A6T+dMgAAwAAAGNvbQAAAAAAAAAAAABwQQ==
            </data>
        </array>
        <array>
            <array>
                <data>
                mJkZQWRmhkFmZjxCNDNZQg==
                </data>
                <data>
                Ai7f3MgA
                </data>
                <data>
                Ay7f3MgAAwAAAGNvbQAAAAAAAAAAAABwQQ==
                </data>
            </array>
            <array>
                <array>
                    <data>
                    ODNzQQAAgEHPzAdCAQALQg==
                    </data>
                    <data>
                    AtNm9MgA
                    </data>
                    <data>
                    A9Nm9MgACgAAAG1vdmVwbGF0ZW4AAAAAAAAA
                    AAAAcEE=
                    </data>
                    <data>
                    Adzc3MgAAAAAAAAAAAACAJZBAgCWQQ==
                    </data>
                </array>
            </array>
        </array>
        <array>
            <data>
            AACAQTMzk0EAALZCzcy6Qg==
            </data>
            <data>
            Av3ZfMgA
            </data>
            <data>
            A/3ZfMgAAwAAAGNvbQAAAAAAAAAAAABwQQ==
            </data>
        </array>
        <array>
            <array>
                <data>
                ZmaGQTQzk0EzM1lCmplfQg==
                </data>
                <data>
                Ap096sgA
                </data>
                <data>
                A5096sgACgAAAG1vdmVwbGF0ZW4AAAAAAAAAAAAAcEE=
                </data>
                <data>
                Adzc3MgAAAAAAAAAAAAAABZCAAAWQg==
                </data>
            </array>
        </array>
    </array>
    <array>
        <data>
        AABsQ2ZmBkIAAMFDmpk3Qw==
        </data>
        <data>
        Av3ZfMgA
        </data>
        <data>
        A/3ZfMgAAwAAAGNvbQAAAAAAAAAAAABwQQ==
        </data>
    </array>
    <array>
        <array>
            <data>
            AACAQZyZWUEAALZCNDOxQg==
            </data>
            <data>
            ApZGE8gA
            </data>
            <data>
            A5ZGE8gABgAAAGdpdGh1YgAAAAAAAAAAAABwQQ==
            </data>
            <data>
            Adzc3MgAAAAAAAAAAAAAAJZCAACWQg==
            </data>
        </array>
        <array>
            <array>
                <data>
                YGYmQQAAgEGYmT9CAABWQg==
                </data>
                <data>
                Airf68gA
                </data>
                <data>
                Ayrf68gACgAAAG1vdmVwbGF0ZW4AAAAAAAAAAAAAcEE=
                </data>
                <data>
                Adzc3MgAAAAAAAAAAAAAABZCAAAWQg==
                </data>
            </array>
        </array>
        <array>
            <data>
            mJmhQgEAyELMzBtDAAAvQw==
            </data>
            <data>
            Avcj78gA
            </data>
            <data>
            A/cj78gAAwAAAGNvbQAAAAAAAAAAAABwQQ==
            </data>
        </array>
        <array>
            <array>
                <data>
                QDNzQcDMDEHQzFJCMDM5Qg==
                </data>
                <data>
                Ar/r78gA
                </data>
                <data>
                A7/r78gABgAAAGdpdGh1YgAAAAAAAAAAAABwQQ==
                </data>
                <data>
                Adzc3MgAAAAAAAAAAAAAABZCAAAWQg==
                </data>
            </array>
            <array>
                <array>
                    <data>
                    wMxMQXBmZkFgZvxBnJkEQg==
                    </data>
                    <data>
                    ArJiKMgA
                    </data>
                    <data>
                    A7JiKMgAAwAAAGNvbQAAAAAAAAAAAABwQQ==
                    </data>
                </array>
            </array>
        </array>
    </array>
    <array>
        <data>
        AADAQTMza0MAAC5DmpnAQw==
        </data>
        <data>
        Ap096sgA
        </data>
        <data>
        A5096sgACgAAAG1vdmVwbGF0ZW4AAAAAAAAAAAAAcEE=
        </data>
        <data>
        Adzc3MgAAAAAAAAAAAAAABZDAQAWQw==
        </data>
    </array>
    <array>
        <array>
            <data>
            AACAQHBmZkEAAJ5Cz8yyQg==
            </data>
            <data>
            ApXLu8gA
            </data>
            <data>
            A5XLu8gACAAAAG5vZGV2bWFwAAAAAAAAAAAAAHBB
            </data>
        </array>
        <array>
            <array>
                <data>
                zMxMQTAzk0EzM0lCmJlfQg==
                </data>
                <data>
                AuD6/MgA
                </data>
                <data>
                A+D6/MgAAwAAAGNvbQAAAAAAAAAAAABwQQ==
                </data>
            </array>
        </array>
        <array>
            <data>
            MzO7QjQzI0KamShDm5nnQg==
            </data>
            <data>
            AtT76MgA
            </data>
            <data>
            A9T76MgABgAAAGdpdGh1YgAAAAAAAAAAAABwQQ==
            </data>
            <data>
            Adzc3MgAAAAAAAAAAAABAJZCAQCWQg==
            </data>
        </array>
        <array>
            <array>
                <data>
                aGZmQUAzc0GbmU9C0MxSQg==
                </data>
                <data>
                Avx+F8gA
                </data>
                <data>
                A/x+F8gAAwAAAGNvbQAAAAAAAAAAAABwQQ==
                </data>
            </array>
        </array>
    </array>
    <array>
        <data>
        ZmZyQwAAcEMzM8RDAADDQw==
        </data>
        <data>
        AhHhH8gA
        </data>
        <data>
        AxHhH8gACAAAAG5vZGV2bWFwAAAAAAAAAAAAAHBB
        </data>
    </array>
    <array>
        <array>
            <data>
            AABAQTAzc0EAAK5CZma0Qg==
            </data>
            <data>
            Avj+0cgA
            </data>
            <data>
            A/j+0cgAAwAAAGNvbQAAAAAAAAAAAABwQQ==
            </data>
        </array>
        <array>
            <array>
                <data>
                QDOzQNDMTEFoZixCNjNJQg==
                </data>
                <data>
                AmxUz8gA
                </data>
                <data>
                A2xUz8gABgAAAGdpdGh1YgAAAAAAAAAAAABwQQ==
                </data>
                <data>
                Adzc3MgAAAAAAAAAAAAAABZCAgAWQg==
                </data>
            </array>
        </array>
        <array>
            <data>
            zMy8QjAzI0JmZilDmJnnQg==
            </data>
            <data>
            AvTcOsgA
            </data>
            <data>
            A/TcOsgACgAAAG1vdmVwbGF0ZW4AAAAAAAAAAAAAcEE=
            </data>
            <data>
            Adzc3MgAAAAAAAAAAAAAAJZCAACWQg==
            </data>
        </array>
        <array>
            <array>
                <data>
                AABAQdDMjEEAAEZCaGZcQg==
                </data>
                <data>
                Atw4T8gA
                </data>
                <data>
                A9w4T8gABgAAAGdpdGh1YgAAAAAAAAAAAABwQQ==
                </data>
                <data>
                Adzc3MgAAAAAAAAAAAAAABZCAAAWQg==
                </data>
            </array>
            <array>
                <array>
                    <data>
                    AABAQdDMjEEAAPZBaGYRQg==
                    </data>
                    <data>
                    Aue38cgA
                    </data>
                    <data>
                    A+e38cgAAwAAAGNvbQAAAAAAAAAAAABwQQ==
                    </data>
                </array>
            </array>
        </array>
    </array>
</array>
</plist>

)
